### PR TITLE
FullScreen

### PR DESCRIPTION
**Pull request by ppamorim**
@pedrovgs I'm facing some problems with the slide and touch issues. I need create a Sequencer animation on Rebound to provide a better look for this animation. But what we have now is amazing!

I need some help!

### CODE REVIEW

**Comment by ppamorim** [comment]
@pedrovgs Remember, it's a unstable code yet, but is the base of this animation. You can see this animation at Tv Shows Activity.

**Comment by ppamorim** [comment]
@pedrovgs Do you noticed any problem with ViewCompat.setPivotX? Here's a strange problem.

error

**Comment by jumpsH** [comment]
lol  hhhhhhhhha ^-^

**Comment by tanaev** [comment]
@ppamorim hi! How you solve problem from previous comment?

**Comment by ppamorim** [comment]
Yes, don`t use the class ViewCompat.

**Comment by tanaev** [comment]
@ppamorim  cool! Where i can found example?

**Comment by ppamorim** [comment]
Yes!

https://gist.github.com/ppamorim/c5a003495295cab9ae4b

**Comment by tanaev** [comment]
Good! One more question! 

Where i can get 

SpringSequencer, ZoomListener, RotateCallback 

?

**Comment by Mariovc** [comment]
The videoView goes out of the screen (to the right of it) while a black background is perfectly rotated and transalated.

Seems to be working on my phone with "TV Shows" but not with "VideoView". 

Testing with Android 5.1. Is it working for you, guys?

**Pull request closed without merging**
