### PR TITLE
add getHorizontalDragRange() to get horizontal draggable mount, and f…

### PR DESCRIPTION
**Pull request by eneim**
…ix changeDragViewAlpha()

**Changed**

gradle version to 1.2.3

change getHorizontalDragOffset() and add getHorizontalDragRange()

Please checkout.

### CODE REVIEW

**Comment by pedrovgs** [comment]
The build of this branch is broken in Travis-CI. Can you take a look?

**Comment by eneim** [comment]
@pedrovgs Oh so sorry, I push this right before my bed time. Not many experiences with Travis, but I'll fix it. It seems to be errors related to gradle version and Android Build Tools version.

**Comment by eneim** [comment]
Hm, I 'changed' your travis.yml but it turns out not to be a good try, since It will affect others' PR and may cause more problems. I will revert it and fix my local build tool. Pardon me!

**Comment by eneim** [comment]
hm @pedrovgs , using Math.abs(dragView.getLeft()) to get horizontal alpha when you drag the view to the left will end up an unexpected value when the view's left bound out of screen (its left value become negative then the alpha will increase). Is that your expected value? Or else I think we can use

```
(dragView.getRight() - dragView.getLeft())/2
```

which will use dragView's center location to determine alpha value, which I suppose could get better alpha effect.

I found some other math stuff that need to be corrected too, please tell me if you are pleasure if I take care of them.

Best regard.

**Comment by eneim** [comment]
I'll create a better PR later

**Pull request closed without merging**
